# Generated by Django 5.0.6 on 2024-06-26 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                help_text="выберите курс",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson_set",
                to="materials.course",
                verbose_name="курс",
            ),
        ),
    ]
