# Generated by Django 5.0.6 on 2024-08-02 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0006_course_created_at_course_updated_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="is_subscribed",
        ),
    ]
